### ISSUE TITLE
FITS file export fails

### ISSUE THREAD

**Issue by tmolteno** [tmolteno/spotless#1]
The command
```
spotless --display --fits
```
fails with
```
Traceback (most recent call last):
  File "/home/tim/.local/bin/spotless", line 172, in <module>
    handle_image(ARGS, None, "gridless", time_repr, src_list)
  File "/home/tim/.local/bin/spotless", line 42, in handle_image
    api_imaging.save_fits_image(img, fname=fname, out_dir=args.dir, timestamp=time_repr)
  File "/home/tim/.local/lib/python3.10/site-packages/tart_tools/api_imaging.py", line 175, in save_fits_image
    hdu = pyfits.PrimaryHDU(img.astype(np.float32))
AttributeError: 'NoneType' object has no attribute 'astype'
```

**Comment by tmolteno** [comment]
Upon investigation, this should be solved by exposing disko sphere object, and using that with spotless

https://github.com/tmolteno/disko/issues/10
